export default {
  array: "object",
/*  blob: */
  boolean: "boolean",
  datetime: "date",
  embedded: "object",
  f64: "number",
  i8: "number",
  i16: "number",
  i32: "number",
  i64: "bigint",
  i128: "bigint",
  json: "string",
  primary: "primary",
  string: "string",
  time: "date",
  u8: "number",
  u16: "number",
  u32: "number",
  u64: "bigint",
  u128: "bigint",
  uuid: "string",
};
